task create_game_rules: :environment do
  GameRule.create(name: "Speed 50mph")
  GameRule.create(name: "Speed 60mph")
  GameRule.create(name: "Speed 70mph")
  GameRule.create(name: "Speed 80mph")
  GameRule.create(name: "Speed 90mph")
  GameRule.create(name: "Distance 60ft")
  GameRule.create(name: "Distance 45ft")
  GameRule.create(name: "Distance 35ft")
  GameRule.create(name: "Pitching Machine", description: "All facilities must use a pitching macine.")
  GameRule.create(name: "Live Pitching", description: "All facilities must use a live pitcher.")
  GameRule.create(name: "Baseball")
  GameRule.create(name: "Softball")
  GameRule.create(name: "Fast Pitch")
  GameRule.create(name: "Cage Ball")
  GameRule.create(name: "Bat Type: Wood")
  GameRule.create(name: "Bat Type: Metal")
  GameRule.create(name: "Bat Type: BBCOR")
  GameRule.create(name: "Age Group: 10u")
  GameRule.create(name: "Age Group: 14u")
  GameRule.create(name: "Age Group: 18u")
  GameRule.create(name: "Age Group: College")
  GameRule.create(name: "Age Group: Adult")
  GameRule.create(name: "Skill Level: Little League")
  GameRule.create(name: "Skill Level: High School League")
  GameRule.create(name: "Skill Level: Collegiate")
  GameRule.create(name: "Skill Level: Semi-Pro")
  GameRule.create(name: "Skill Level: Professional")
end
