default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  socket: /tmp/mysql.sock
  reconnect: true

development:
  <<: *default
  database: hittrax_tournaments_development
  username: root
  password: <%= ENV['local_database_password'] %>

test:
  <<: *default
  database: hittrax_tournaments_test
  username: root
  password: <%= ENV['local_database_password'] %>

production:
  adapter: mysql2
  database: hittrax_centralDB
  username: <%= ENV['hittrax_username'] %>
  password: <%= ENV['hittrax_password'] %>
  host: <%= ENV['host'] %>
  port: 3306
