default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  socket: /tmp/mysql.sock
  reconnect: true

development:
  <<: *default
  database: hittrax_tournaments_development
  username: root
  password: <%= ENV['DATABASE_PASSWORD'] %>

test:
  <<: *default
  database: hittrax_tournaments_test
  username: root
  password: <%= ENV['DATABASE_PASSWORD'] %>

production:
  adapter: mysql2
  database: hittrax_centralDB
  username: <%= ENV['USERNAME'] %>
  password: <%= ENV['PASSWORD'] %>
  host: hittraxstatscenter.com
  port: 3306
