# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 806779cc997cd0673630052ef554366caa1cabbf9a56f647ade461a9a1a90c3aadf823e9a7aeb73e4d185f9fc553b0fb8b727133db9f25b1f776f572ccb44b47
test:
  secret_key_base: 806779cc997cd0673630052ef554366caa1cabbf9a56f647ade461a9a1a90c3aadf823e9a7aeb73e4d185f9fc553b0fb8b727133db9f25b1f776f572ccb44b47

# Do not keep production secrets in the repository,
# instead read values from the environment.
staging:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
